name: website update

on: 
  push:
    branches: 
      - main

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    steps:

      - name: Send update notification
        run: curl -L "${{ secrets.UPDATE_URL }}"